// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moneta.Api.Infrastructure;

#nullable disable

namespace Moneta.Api.Migrations
{
    [DbContext(typeof(MonetaDbContext))]
    [Migration("20260623122006_MpsReferenceData")]
    partial class MpsReferenceData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Moneta.Api.Domain.Actual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommitmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Consultant")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentRefId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommitmentId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaymentRefId");

                    b.ToTable("Actuals");
                });

            modelBuilder.Entity("Moneta.Api.Domain.Appropriation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CaAmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreditOrigin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<long>("PaAmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentRefId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaymentRefId");

                    b.ToTable("Appropriations");
                });

            modelBuilder.Entity("Moneta.Api.Domain.CategoryMpsMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Excluded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MpsCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskmanCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskmanProject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FiscalYear", "TaskmanProject", "TaskmanCategory")
                        .IsUnique();

                    b.ToTable("CategoryMpsMaps");
                });

            modelBuilder.Entity("Moneta.Api.Domain.Commitment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Counterparty")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentRefId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaymentRefId");

                    b.ToTable("Commitments");
                });

            modelBuilder.Entity("Moneta.Api.Domain.Contractor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Profile")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaskmanUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Contractors");
                });

            modelBuilder.Entity("Moneta.Api.Domain.FiscalYear", b =>
                {
                    b.Property<int>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Year");

                    b.ToTable("FiscalYears");
                });

            modelBuilder.Entity("Moneta.Api.Domain.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClaimedAmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Consultant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoiceRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaymentRefId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReceivedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerifiedBy")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaymentRefId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Moneta.Api.Domain.InvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ClaimedAmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PaymentRefId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaymentRefId");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("Moneta.Api.Domain.MpsCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rollup")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FiscalYear", "Code")
                        .IsUnique();

                    b.ToTable("MpsCodes");
                });

            modelBuilder.Entity("Moneta.Api.Domain.PaymentRef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentRefId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FiscalYear", "PaymentRefId")
                        .IsUnique();

                    b.ToTable("PaymentRefs");
                });

            modelBuilder.Entity("Moneta.Api.Domain.RateCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DailyRateCents")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("IntraMurosRateCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Company", "Profile")
                        .IsUnique();

                    b.ToTable("RateCards");
                });

            modelBuilder.Entity("Moneta.Api.Domain.TaskmanCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttributionStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ComputedAmountCents")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Consultant")
                        .HasColumnType("TEXT");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalRef")
                        .HasColumnType("TEXT");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Hours")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaymentRefId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskmanCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskmanProject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TaskmanUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExternalRef")
                        .IsUnique();

                    b.HasIndex("PaymentRefId");

                    b.ToTable("TaskmanCosts");
                });

            modelBuilder.Entity("Moneta.Api.Domain.TaskmanProject", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSynced")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.ToTable("TaskmanProjects");
                });

            modelBuilder.Entity("Moneta.Api.Domain.Actual", b =>
                {
                    b.HasOne("Moneta.Api.Domain.Commitment", "Commitment")
                        .WithMany("Actuals")
                        .HasForeignKey("CommitmentId");

                    b.HasOne("Moneta.Api.Domain.Invoice", "Invoice")
                        .WithMany("Actuals")
                        .HasForeignKey("InvoiceId");

                    b.HasOne("Moneta.Api.Domain.PaymentRef", "PaymentRef")
                        .WithMany("Actuals")
                        .HasForeignKey("PaymentRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commitment");

                    b.Navigation("Invoice");

                    b.Navigation("PaymentRef");
                });

            modelBuilder.Entity("Moneta.Api.Domain.Appropriation", b =>
                {
                    b.HasOne("Moneta.Api.Domain.PaymentRef", "PaymentRef")
                        .WithMany("Appropriations")
                        .HasForeignKey("PaymentRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentRef");
                });

            modelBuilder.Entity("Moneta.Api.Domain.Commitment", b =>
                {
                    b.HasOne("Moneta.Api.Domain.PaymentRef", "PaymentRef")
                        .WithMany("Commitments")
                        .HasForeignKey("PaymentRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentRef");
                });

            modelBuilder.Entity("Moneta.Api.Domain.Invoice", b =>
                {
                    b.HasOne("Moneta.Api.Domain.PaymentRef", "PaymentRef")
                        .WithMany("Invoices")
                        .HasForeignKey("PaymentRefId");

                    b.Navigation("PaymentRef");
                });

            modelBuilder.Entity("Moneta.Api.Domain.InvoiceLine", b =>
                {
                    b.HasOne("Moneta.Api.Domain.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Moneta.Api.Domain.PaymentRef", "PaymentRef")
                        .WithMany()
                        .HasForeignKey("PaymentRefId");

                    b.Navigation("Invoice");

                    b.Navigation("PaymentRef");
                });

            modelBuilder.Entity("Moneta.Api.Domain.PaymentRef", b =>
                {
                    b.HasOne("Moneta.Api.Domain.FiscalYear", "Year")
                        .WithMany("PaymentRefs")
                        .HasForeignKey("FiscalYear")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Year");
                });

            modelBuilder.Entity("Moneta.Api.Domain.TaskmanCost", b =>
                {
                    b.HasOne("Moneta.Api.Domain.PaymentRef", "PaymentRef")
                        .WithMany("TaskmanCosts")
                        .HasForeignKey("PaymentRefId");

                    b.Navigation("PaymentRef");
                });

            modelBuilder.Entity("Moneta.Api.Domain.Commitment", b =>
                {
                    b.Navigation("Actuals");
                });

            modelBuilder.Entity("Moneta.Api.Domain.FiscalYear", b =>
                {
                    b.Navigation("PaymentRefs");
                });

            modelBuilder.Entity("Moneta.Api.Domain.Invoice", b =>
                {
                    b.Navigation("Actuals");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Moneta.Api.Domain.PaymentRef", b =>
                {
                    b.Navigation("Actuals");

                    b.Navigation("Appropriations");

                    b.Navigation("Commitments");

                    b.Navigation("Invoices");

                    b.Navigation("TaskmanCosts");
                });
#pragma warning restore 612, 618
        }
    }
}
